
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-argo
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/zoldycksh/erwepifa-argocd.git
    path: .
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true